{
 "title": "Container Probes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Container unreadiness correlated to failures in readiness probes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(prober_probe_total{probe_type=\"Readiness\",result=\"failed\"}[5m]) * on(namespace,pod,container) group_left rate(kube_pod_container_status_ready[5m]))>0",
     "legendFormat": "{{namespace}} - {{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "Liveness probe failures",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prober_probe_total{probe_type=\"Liveness\",result=\"failed\"}[5m])>0",
     "legendFormat": "{{namespace}} - {{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "Container restarts correlated to failures in liveness probes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(prober_probe_total{probe_type=\"Liveness\",result=\"failed\"}[5m]) * \n    on(namespace,pod,container) group_left\n    rate(kube_pod_container_status_restarts_total[5m]))>0",
     "legendFormat": "{{namespace}} - {{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "Liveness probe failures correlated with CPU throttling",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(prober_probe_total{probe_type=\"Liveness\",result=\"failed\"}[5m]) * on(namespace,pod,container) group_right rate(container_cpu_cfs_throttled_periods_total[5m]))>0",
     "legendFormat": "{{namespace}} - {{pod}} / {{container}}"
    }
   ]
  }
 ]
}